### ISSUE TITLE
Survey error? QID35 date formatting

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#10]
The example date is ambiguous between mm/dd/yy and dd/mm/yy formatting. 

```
Bijvoorbeeld: Nasofaryngeaal, 4-1-20, Positief.
```

**Comment by boeveAJ** [comment]
kun je in de excelfile zien wat het format is?? moet idd wel duidelijk worden

**Comment by msteenhagen** [comment]
Goed idee!

**Comment by msteenhagen** [comment]
Ik heb het nu zo opgelost (ik zal dit ook aan AA doorgeven): 

There’s an issue with date formatting in QID35_QuestionText. In the Netherlands and Belgium, the standard is dd/mm/yy. But if you simply ask people to fill out a numerical date, the data will be ambiguous. I have in the translation suggested that they write down the date as: 1 April ’20. (Instead of 4-1-20 or 1-4-20.)
