### ISSUE TITLE
Vertaling? QID39 - 'titerwaarde'

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#13]
Is 'titerwaarde' een gangbaar begrip? (Wordt dit genoemd in testuitslag van serologische tests?)

```
QID39_QuestionText,"Als uw uitslag positief was en uw testresultaat noemde een titerwaarde, wat was de waarde voor IgM?&nbsp;"
```

**Comment by msteenhagen** [comment]
Komt op 6 plaatsen voor (allemaal in het stuk over antistoffen)

**Comment by jjljacobs** [comment]
Titer is gangbaar jargon. Voor leken waarschijnlijk niet duidelijk. Het is 1 / concentratie (de verdunning waarbij je iets nog kunt meten)..

**Comment by msteenhagen** [comment]
Ok, prima! Bedankt
