### ISSUE TITLE
Survey error? QID336

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#14]
Answering 'Geen van deze' would be contradictory, given that this question presupposes that there are memory symptoms. 
```
QID336_Choice1,"Verlies kortetermijngeheugen (geheugen dat ~30 seconden blijft, bijv. een telefoonnummer onthouden voor u het opschrijft, or vergeten met welke taak u bezig was)"
QID336_Choice2,"Verlies langetermijngeheugen (langetermijngeheugen loopt uiteen van het herinneren van de voorgaande dag, vergeten dat u een taak heeft uitgevoerd, het vergeten van onlangs geleerde informatie, of uw basisschoolervaring niet meer kunnen herinneren.)"
QID336_Choice3,Geen nieuwe herinneringen meer kunnen vormen
QID336_Choice4,"Vergeten hoe normale taken gedaan moeten worden (veters strikken, handen wassen)"
QID336_Choice5,Anders
QID336_Choice6,Geen van deze
```

**Comment by boeveAJ** [comment]
Er lijken wat " ... " te ontbreken ook? moeg het even in context zien ook denk ik

**Comment by msteenhagen** [comment]
Ja, het is een beetje een rommeltje :) In de Engelse versie hebben ze alleen "..." gebruikt voor tekst met komma's. Ik heb geprobeerd de boel zoveel mogelijk intact te laten, en dus zijn niet alle tekstvelden met "..." omsloten. Ik heb de instructie gekregen om zo min mogelijk van de formatting te wijzigen. ¯\_(ツ)_/¯
