### ISSUE TITLE
Vertaling? QID347 Tremors en bevend gevoel

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#15]
QID347 en daaromheen. Ik vertaal nu 'vibrating sensation' met 'bevend gevoel' (een Nederlandse term die ik wel op internet tegenkwam in de context van Covid-19). Is dit duidelijk? Er wordt ook een omschrijving geboden in de enquête. 

```
<strong>Tremor</strong>: Onwillekeurige, ritmische spiersamentrekking die leidt tot een schuddende beweging in één of meerdere lichaamsdelen&nbsp;</div>➘➘<div><strong>Bevend gevoel</strong>: Een trillende sensatie, die voelt alsof uw spieren, vingers, of benen&nbsp;vibreren&nbsp;of schudden van binnen, maar u ziet geen beweging&nbsp;</div>"
```

**Comment by boeveAJ** [comment]
trillingen ?

**Comment by msteenhagen** [comment]
Dan maak ik er 'trillend gevoel' van (de definitie ervan laat open dat er niets écht trilt, alleen dat het zo voelt)
