### ISSUE TITLE
Vertaling? QID376 'Brain Fog'

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#16]
Ik heb in QID376 en daaromheen het Engelse 'brain fog' onvertaald gelaten, en alleen in aanhalingstekens gezet. Wat ik begrijp is dit (nog) geen klinische term, en is het voornamelijk uit patiënten voortgekomen. De Engelse term wordt volgens mij ook in Nederland gebruikt. 

(Ik heb één Nederlandse vertaling tussen haakjes genoemd, 'hersenmist'.)

```
V,QID376_QuestionText,"<span style=""font-family:Arial,Helvetica,sans-serif;"">Heeft u problemen gehad met <strong>'BRAIN FOG' (HERSENMIST)</strong>&nbsp;(onvermogen om te concentreren, om te denken, om te plannen, om een gedachtengang te verwerken, begrijpen, en vol te houden; abnormaal langzame of snelle gedachten)&nbsp;sinds het begin van uw ziekte met COVID-19?&nbsp;<span style=""color:#e74c3c;"">*</span></span>"
```

**Comment by jjljacobs** [comment]
Brain fog = concentratieproblemen.

**Comment by boeveAJ** [comment]
wazig in je hoofd

**Comment by msteenhagen** [comment]
Goed, ik voeg concentratieproblemen toe. Ik laat brain fog ook wel staan, omdat dit op de internetfora nu overal een gangbare term lijkt te zijn.
