### ISSUE TITLE
Vertaling? QID430 'uw pre-COVID-baseline'

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#17]
Is het duidelijk om dit min of meer onvertaald te laten: 'pre-COVID-baseline'

```
,QID430_QuestionText,"Hoe zou u zeggen dat u zich vandaag voelt, op een schaal van 0-100% (waarbij 100% uw pre-COVID-baseline is)?➘&nbsp;"
```

**Comment by jjljacobs** [comment]
waarbij 100% was hoe u zich voelde voordat u COVID had (pre-COVID-baseline).

**Comment by boeveAJ** [comment]
waarbij 100% uw basis gezondheid voorafgaand aan uw corona besmetting weergeeft

**Comment by msteenhagen** [comment]
Bedankt! Dan voeg ik het als volgt samen: 'waarbij 100% weergeeft hoe u zich voelde voordat u COVID had' 

(Ik zie nu dat de term 'pre-Covid-baseline' niet vaker voorkomt, dus het voegt weinig toe om die erin te laten.)
