### ISSUE TITLE
Vertaling? Stedelijke gebieden: betere vertaling dan dit? (QID219)

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#2]
V,QID219_Choice1,Suburban
V,QID219_Choice2,Urban
V,QID219_Choice3,Rural

V,QID219_Choice1,Randgemeente
V,QID219_Choice2,Stad
V,QID219_Choice3,Platteland

**Comment by boeveAJ** [comment]
urbanisatiegraad cbs maar dan in beperktere vorm? zeer sterk stedelijk , sterk stedelijk, matig stedelijk, weinig stedelijk, en niet stedelijk. 

ik vind jou drie opties eigenlijk beter denk ik

**Comment by msteenhagen** [comment]
Ok, bedankt. Dan houd ik het hierbij. Bedankt!
