### ISSUE TITLE
Vertaling? QID228 "Wat is uw hoogst afgeronde opleiding?

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#5]
Hier weet ik niet zeker of dit goed is: 

 ,QID228_Choice1,Middelbare school niet afgemaakt (voor: Some high school or less) <---???
 ,QID228_Choice2,Middelbare school
 ,QID228_Choice3,Bachelor-opleiding
 ,QID228_Choice4,Master-opleiding of hoger

**Comment by jjljacobs** [comment]
Middelbare school + MBO?

**Comment by boeveAJ** [comment]
Voor Nederland is dit te summier kwa antwoord opties. Ik ga hier later dit weekend nog een suggestie voor doen

**Comment by msteenhagen** [comment]
Ok, het probleem zit echt in de Engelse versie (op VS gebaseerd). Ik heb er maar dit van gemaakt, en zo moet het dan maar

```
QID228_Choice1,Geen schoolopleiding voltooid na de lagere school
QID228_Choice2,Middelbare school of MBO
QID228_Choice3,Bachelor-opleiding (HBO of WO)
QID228_Choice4,Master-opleiding of hoger (HBO of WO)
```
