### ISSUE TITLE
Vertaling? QID24 - PCR testbeschrijving 

### ISSUE THREAD

**Issue by msteenhagen** [msteenhagen/vertaling-covid-vragenlijst#9]
Nasaal en Nasofaryngeaal zijn hier onderscheiden van Keel. Maar Nasofaryngeaal neemt ook slijm uit keel. Is dit duidelijk genoeg zo?

```
QID24_Choice1,"Nasaal (neusslijm van de neusvleugels, zonder afname diep in de neus en keel)"
QID24_Choice2,"Nasofaryngeaal (neusslijm van achteraan de neusvleugels, met afname diep in de neus en keel)<br />➘<br />➘<img src=""https://qfreeaccountssjc1.az1.qualtrics.com/CP/Graphic.php?IM=IM_1Y88OHV4v4cQAND"" style=""width: 270px; height: 207px;"" />"
QID24_Choice3,Keel
```

**Comment by msteenhagen** [comment]
These choices will return twice. Make sure translations are uniform

**Comment by msteenhagen** [comment]
![Diagnosis+image1](https://user-images.githubusercontent.com/2271178/93326524-38db7a00-f819-11ea-846f-5b8ef23f757e.jpeg)

I see there's a graphic part of the question too (for Nasofaryngeaal).

**Comment by jjljacobs** [comment]
nasaal = neus
Nasofaryngeaal = keel-neus

**Comment by msteenhagen** [comment]
Dus zou dit beter zijn? 

```
QID24_Choice1, Neus (neusslijm van de neusvleugels, zonder afname diep in de neus en keel)
QID24_Choice2, Keel-neus (neusslijm van achteraan de neusvleugels, met afname diep in de neus en keel)
QID24_Choice3, Keel
```

Dit hangt samen met die andere vraag die ik had over PCR tests. Gaat een nasofaryngeale test alleen via de neus, of ook via de mond? (Ik krijg de indruk dat de beschrijving in de originele enquête ervan uitgaat dat het alleen via de neus gaat, dus dat ze geen optie 'neus en keel' hebben, alleen dus: 'via neus voorin', 'via neus diep achteraan', 'via keel'. Of maakt dit uiteindelijk niet zoveel uit?)

```
QID24_Choice1,  Nasal (nasal secretions from nostrils, without moving forward into the back of the nose and throat)
QID24_Choice2,  Nasopharyngeal (nasal secretions from end of the nostrils, by moving to the cavity in back of the nose and throat)
QID24_Choice3, Throat
```

**Comment by msteenhagen** [comment]
Ah, ik heb in een Belgisch instructiedocument het probleem gevonden. Er zijn dus verschillende manieren van het afnemen van stalen voor PCR Sars-nCov-2:

Diepe neuswissers (nasofaryngeale wissers)
Keelwissers (orofaryngeale wisser)

In België (en Nederland, denk ik) wordt de keelwisser ook nog eens in de neus gestoken. Het proces in de VS is misschien anders? 

In ieder geval weet ik nu genoeg. 


```
Om een infectie met het nieuwe coronavirus (SARS-CoV-2) aan te tonen wordt een staal van de bovenste luchtwegen afgenomen. Dit kan zowel met een diepe neuswisser (nasofaryngeale wisser) als met een keelwisser (orofaryngeale wisser) omdat het virus zich ter hoogte van beide sites kan vermenigvuldigen.
In deze procedure worden zowel de afname van een diepe neuswisser (nasofaryngeale wisser) als van een gecombineerde keel- en neuswisser (orofarynxwisser + voorste gedeelte van de neus) beschreven.
``
(https://www.zorg-en-gezondheid.be/sites/default/files/atoms/files/COVID-19%20procedure%20afname%20wissers%20v2_09042020.pdf)

**Comment by msteenhagen** [comment]
Ik heb dit weer even open moeten gooien omdat er een nieuwe vraag is. Het onderstaande is in het Engels. 

MS: There’s an issue with the PCR test description (QIDs 24, 28, 32). To my knowledge, in Belgium and in the Netherlands, people are swabbed twice with the same swab, once in the throat with a orofaryngeal swab, and then the same swab is used to take a sample from the front of the nose. In the questionnaire this would strictly count as ‘other’, but I’m not sure which option people who have been swabbed this way will pick. 

```
QID24_QuestionText,"What was the type of your COVID-19 test?
QID24_Choice1,"Nasal (nasal secretions from nostrils, without moving forward into the back of the nose and throat)"
QID24_Choice2,"Nasopharyngeal (nasal secretions from end of the nostrils, by moving to the cavity in back of the nose and throat)"
QID24_Choice3,Throat
QID24_Choice4,Other
```

AA: That's interesting! In some places in the UK a nasopharyngeal swab could be used for throat and back of the nose, and that's why we let multiple choices. **Do you think adding explicit instruction to choose multiple answers would help?**

# Vragen
1. Klopt het dat in België en Nederland mensen in 2 stappen monsters worden genomen: 1x in  de keel met een orofaryngeal swab, en dan nog 1x met hetzelfde staafje van _voorin_ de neus?
2. Zou het duidelijker zijn om bij de bovenstaande enquêtevraag meerde antwoorden toe te staan, zodat mensen die in Nederland getest waren kunnen kiezen voor optie 1 én 2?

**Comment by msteenhagen** [comment]
Antwoorden

1. Nee, niet altijd. Soms met 1 staafje, soms worden er 2 gebruikt. En de neusmonstering is doorgaans wel diep. 
2. Ja.
